# Generated by Django 3.1.1 on 2020-09-25 16:17

from django.db import migrations, models
import stock.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='end_date',
            new_name='buy_date',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='start_date',
            new_name='sell_date',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='update_data',
            new_name='update_date',
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(help_text='Type Stock Symbol HERE', max_length=4, unique=True, validators=[stock.validators.validate_symbol]),
        ),
    ]
