# Generated by Django 3.1.1 on 2020-09-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200926_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='update_date',
            new_name='update_time',
        ),
    ]
