# Generated by Django 3.1.1 on 2020-09-25 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200926_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
