# Generated by Django 3.1.1 on 2020-09-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200926_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='plot',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(help_text='Type Stock Symbol HERE', max_length=4, unique=True),
        ),
    ]
